# Generated by Django 2.0.4 on 2018-07-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='description'),
        ),
    ]
