# Generated by Django 2.0.4 on 2018-07-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_project_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_changed',
            field=models.DateTimeField(auto_now=True, verbose_name='changed date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
    ]
